/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class DetailClass extends javax.swing.JFrame {

    /**
     * Creates new form DetailClass
     */
    public DetailClass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnKembali = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(143, 192, 169));

        jTextField1.setBackground(new java.awt.Color(250, 243, 221));
        jTextField1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(50, 50, 52));
        jTextField1.setText("Ruangan 101");

        jComboBox1.setBackground(new java.awt.Color(250, 243, 221));
        jComboBox1.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(50, 50, 52));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(253, 222, 138));
        btnKembali.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(50, 50, 52));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tabledetail.setBackground(new java.awt.Color(250, 243, 221));
        tabledetail.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tabledetail.setForeground(new java.awt.Color(50, 50, 52));
        tabledetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {
                    { "08.00 - 08.50", "TIF1101", "Pemrograman Berbasis Objek Lanjutan", "3", "MFS", "C", "1" },
                    { "08.50 - 09.40", "TIF1101", "Pengantar Teknologi Informasi", null, "MFS", "C", "1" },
                    { "09.40 - 10.30", "TIF1101", "Pengantar Teknologi Informasi", null, "MFS", "C", "1" },
                    { "10.30 - 11.20", "TIF3110", "Pembelajaran Mesin", "2", "ERN", "B", "5" },
                    { "11.20 - 13.00", "TIF3110", "Pembelajaran Mesin", null, "ERN", "B", "5" },
                    { "12.10 - 13.00", "", null, null, null, null, null },
                    { "13.00 - 13.50", null, null, null, null, null, null },
                    { "13.50 - 14.40", "TIF2108", "Web Semantik", "3", "VEN", "A", "3" },
                    { "14.40 - 15.30", "TIF2108", "Web Semantik", null, "VEN", "A", "3" },
                    { "15.30 - 16.20", "TIF2108", "Web Semantik", null, "VEN", "A", "3" }
            },
            new String[] {
                "Jam ", "Kode MK", "Mata Kuliah", "SKS", "Dosen", "Kelas", "Semester"
            }
        ));
        jScrollPane1.setViewportView(tabledetail);
        if (tabledetail.getColumnModel().getColumnCount() > 0) {
            tabledetail.getColumnModel().getColumn(0).setResizable(false);
            tabledetail.getColumnModel().getColumn(0).setPreferredWidth(150);
            tabledetail.getColumnModel().getColumn(1).setResizable(false);
            tabledetail.getColumnModel().getColumn(2).setResizable(false);
            tabledetail.getColumnModel().getColumn(2).setPreferredWidth(300);
            tabledetail.getColumnModel().getColumn(3).setResizable(false);
            tabledetail.getColumnModel().getColumn(3).setPreferredWidth(40);
            tabledetail.getColumnModel().getColumn(4).setResizable(false);
            tabledetail.getColumnModel().getColumn(5).setResizable(false);
            tabledetail.getColumnModel().getColumn(6).setResizable(false);
        }

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(jTextField1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(jComboBox1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(btnKembali)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36,
                                        Short.MAX_VALUE)
                                .addComponent(btnKembali)
                                .addGap(33, 33, 33)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
        // handling here
    }

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            this.setVisible(false);
            Home home = new Home();
            home.setLocationRelativeTo(null);
            home.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tabledetail;
    // End of variables declaration
}