/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.view;

import com.config.Config;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class DetailClass extends javax.swing.JFrame {
    // custom code
    private static ResultSet result;
    public static String pilihanHari = Config.ubahHari(Config.formattedDate);

    /**
     * Creates new form DetailClass
     */
    public DetailClass() {
        initComponents();

        // mendapatkan data dari database
        try {
            result = Config.getJadwalPerHariDanRuangan(pilihanHari, Home.ruangan);
            while(result.next()){
                // "Jam ", "Kode MK", "Mata Kuliah", "SKS", "Dosen", "Kom", "Semester"
                String jam = result.getString("jam");
                String kode_matkul = result.getString("kode_matkul");
                String nama_matkul = result.getString("nama_matkul");
                String sks = result.getString("sks");
                String kode_dosen = result.getString("kode_dosen");
                String kom = result.getString("kom");
                String semester = result.getString("semester");
                Object tblData[] = {jam, kode_matkul, nama_matkul, sks, kode_dosen, kom, semester};
                DefaultTableModel tblModel = (DefaultTableModel) tblDetail.getModel();
                tblModel.addRow(tblData);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jPanel2 = new javax.swing.JPanel();
        ruanganKelas = new javax.swing.JTextField();
        cmbHari = new javax.swing.JComboBox<>();
        btnKembali = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(143, 192, 169));

        ruanganKelas.setBackground(new java.awt.Color(250, 243, 221));
        ruanganKelas.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        ruanganKelas.setForeground(new java.awt.Color(50, 50, 52));
        ruanganKelas.setText("Ruangan " + Home.ruangan);

        cmbHari.setBackground(new java.awt.Color(250, 243, 221));
        cmbHari.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        cmbHari.setForeground(new java.awt.Color(50, 50, 52));
        cmbHari.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Pilih hari", "Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu" }));
        cmbHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hariActionPerformed(evt);
            }
        });

        btnKembali.setBackground(new java.awt.Color(253, 222, 138));
        btnKembali.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(50, 50, 52));
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        tblDetail.setBackground(new java.awt.Color(250, 243, 221));
        tblDetail.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        tblDetail.setForeground(new java.awt.Color(50, 50, 52));
        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] {
                        "Jam ", "Kode MK", "Mata Kuliah", "SKS", "Dosen", "Kom", "Semester"
                }));
        jScrollPane1.setViewportView(tblDetail);
        if (tblDetail.getColumnModel().getColumnCount() > 0) {
            tblDetail.getColumnModel().getColumn(0).setResizable(false);
            tblDetail.getColumnModel().getColumn(0).setPreferredWidth(150);
            tblDetail.getColumnModel().getColumn(1).setResizable(false);
            tblDetail.getColumnModel().getColumn(2).setResizable(false);
            tblDetail.getColumnModel().getColumn(2).setPreferredWidth(300);
            tblDetail.getColumnModel().getColumn(3).setResizable(false);
            tblDetail.getColumnModel().getColumn(3).setPreferredWidth(40);
            tblDetail.getColumnModel().getColumn(4).setResizable(false);
            tblDetail.getColumnModel().getColumn(5).setResizable(false);
            tblDetail.getColumnModel().getColumn(6).setResizable(false);
        }

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jDesktopPane1Layout.setVerticalGroup(
                jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addComponent(ruanganKelas,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(6, 6, 6)
                                                                .addComponent(cmbHari,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 87,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(btnKembali)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ruanganKelas, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbHari, javax.swing.GroupLayout.PREFERRED_SIZE, 25,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36,
                                        Short.MAX_VALUE)
                                .addComponent(btnKembali)
                                .addGap(33, 33, 33)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>

    private void hariActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            this.setVisible(false);
            pilihanHari = cmbHari.getSelectedItem().toString();;
            DetailClass detailClass = new DetailClass();
            detailClass.setLocationRelativeTo(null);
            detailClass.setVisible(true);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            this.setVisible(false);
            Home home = new Home();
            home.setLocationRelativeTo(null);
            home.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnKembali;
    private javax.swing.JComboBox<String> cmbHari;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ruanganKelas;
    private javax.swing.JTable tblDetail;
    // End of variables declaration
}