package com.view;
import com.config.Config;

public class View {
    public static void index(){
        System.out.println("\nTubes PBOL Kelompok 4");
        System.out.println("\nC-101\n" + "=====\n");
        System.out.println("Senin" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Senin", "C-101"));
        System.out.println("\nSelasa" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Selasa", "C-101"));
        System.out.println("\nRabu" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Rabu", "C-101"));
        System.out.println("\nKamis" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Kamis", "C-101"));
        System.out.println("\nJumat" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Jumat", "C-101"));
        System.out.println("\nC-102\n" + "=====\n");
        System.out.println("Senin" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Senin", "C-102"));
        System.out.println("\nSelasa" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Selasa", "C-102"));
        System.out.println("\nRabu" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Rabu", "C-102"));
        System.out.println("\nKamis" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Kamis", "C-102"));
        System.out.println("\nJumat" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Jumat", "C-102"));
        System.out.println("\nC-103\n" + "=====\n");
        System.out.println("Senin" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Senin", "C-103"));
        System.out.println("\nSelasa" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Selasa", "C-103"));
        System.out.println("\nRabu" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Rabu", "C-103"));
        System.out.println("\nKamis" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Kamis", "C-103"));
        System.out.println("\nJumat" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Jumat", "C-103"));
        System.out.println("\nC-104\n" + "=====\n");
        System.out.println("Senin" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Senin", "C-104"));
        System.out.println("\nSelasa" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Selasa", "C-104"));
        System.out.println("\nRabu" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Rabu", "C-104"));
        System.out.println("\nKamis" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Kamis", "C-104"));
        System.out.println("\nJumat" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Jumat", "C-104"));
        System.out.println("\nC-105\n" + "=====\n");
        System.out.println("Senin" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Senin", "C-105"));
        System.out.println("\nSelasa" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Selasa", "C-105"));
        System.out.println("\nRabu" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Rabu", "C-105"));
        System.out.println("\nKamis" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Kamis", "C-105"));
        System.out.println("\nJumat" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Jumat", "C-105"));
        System.out.println("\nC-106\n" + "=====\n");
        System.out.println("Senin" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Senin", "C-106"));
        System.out.println("\nSelasa" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Selasa", "C-106"));
        System.out.println("\nRabu" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Rabu", "C-106"));
        System.out.println("\nKamis" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Kamis", "C-106"));
        System.out.println("\nJumat" + "\n------");
        System.out.println(Config.getJadwalPerHariDanRuangan("Jumat", "C-106"));
    }
}